spring.application.name=abacus

spring.frontend.url=http://localhost:5173

spring.config.import=optional:file:.env[.properties]

server.servlet.context-path=/api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/abacus}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:abacus_app}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:abacus_app}

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
